### ISSUE TITLE
Support for Stripe SEPA debit payments

### ISSUE THREAD

**Issue by Ramblurr** [killbill/killbill-stripe-plugin#13]
I'm guessing since it isn't explicitly stated that this plugin doesn't support Stripe SEPA debit payments (https://stripe.com/docs/sources/sepa-debit)?

This would be a huge boon for our KB integration. Unfortunately we're a Java/Python/Javascript shop, so I'm not sure we would be able to contribute that to this Ruby plugin. Is there a Stripe payments plugin in Java?

**Comment by pierre** [comment]
> I'm guessing since it isn't explicitly stated that this plugin doesn't support Stripe SEPA debit payments (https://stripe.com/docs/sources/sepa-debit)?

Indeed, `SEPA` isn't supported yet.

> This would be a huge boon for our KB integration. Unfortunately we're a Java/Python/Javascript shop, so I'm not sure we would be able to contribute that to this Ruby plugin.

FWIW, a first-time contributor recently added support for `ACH`, see https://groups.google.com/forum/#!topic/killbilling-users/rdr6uP0E9Lc and https://github.com/killbill/killbill-stripe-plugin/pull/12 for background. I suspect the work would be very similar.

> Is there a Stripe payments plugin in Java?

Not yet, but a re-implementation in Java has been in the back of our minds for a long time, as the plugin would benefit from a lot of the new features provided by the https://github.com/killbill/killbill-plugin-framework-java library. If you are interested in contributing, the [Adyen](https://github.com/killbill/killbill-adyen-plugin) and (albeit a bit older) [Authorize.Net](http://womply2.squarespace.com/press-12/2016/9/23/9aomrzzs8z136ezstktf4dj73o6lpf) plugins are probably good starting points.

**Comment by pierre** [comment]
> Not yet, but a re-implementation in Java has been in the back of our minds for a long time

The re-implementation will be available shortly as part of the upcoming release of Kill Bill 0.22. SEPA will now be supported.
