### ISSUE TITLE
Support for Stripe Connect?

### ISSUE THREAD

**Issue by xquangdang** [killbill/killbill-stripe-plugin#16]
We using stripe to manage billing subscription in our platform. I wonder if killbill-stripe support "[Stripe Connect](https://stripe.com/docs/connect)"? If it does, where I can find the documentation for that?

**Comment by pierre** [comment]
The configuration settings for Connect is described in the [README](https://github.com/killbill/killbill-stripe-plugin/blob/master/README.md#configuration).

Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead for implementation questions. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
