### ISSUE TITLE
Support for Stripe's Strong Customer Authentication (SCA)

### ISSUE THREAD

**Issue by GregOriol** [killbill/killbill-stripe-plugin#19]
Stripe is starting to provide details on new ways to handle payments to comply with an upcoming Strong Customer Authentication (SCA) regulation for September 2019: https://stripe.com/docs/strong-customer-authentication

It seems that:
* the current tokenization using the old checkout form/js as shown in the demo (https://github.com/killbill/killbill-stripe-demo) won't support it (+ also the old checkout form/js is deprecated for some time now)
* there could be a way to still use the old checkout form/js but it is not recommended (https://stripe.com/docs/payments/payment-intents/migration#saving-cards-checkout)
* there are new APIs on Stripe called "Payment Intents" that would be used to have the same feature set for charges that we use today; the major change would be that charges become a 2 step action
* it seems that there will be a need to handle action requests (aka 3D Secure) on payments triggered by killbill on an off-session basis (ie. subscription payments triggered when the user is not using our website), like sending an email to the user and showing them a page with the authentication form...

How would this work with KillBill?

**Comment by pierre** [comment]
Hi @GregOriol,

The short story is that the plugin would need to be updated. All of these flows are already supported in Kill Bill, including 3D-S and generic 2 Step payments flows: it's _just_ a matter of wiring the plugin into the right APIs.

Note that the work would be **much** easier if the plugin were to be rewritten in Java, as we already have lots of boilerplate code to do all of this. To be frank, when we originally auto-generated that plugin in Ruby, we never thought it would become so popular. A Java rewrite would make sense regardless (if only for performance reasons).

Now, this work isn't on our immediate radar, but if that's a blocker for you, feel free to reach out by email and we'll see what we could do.

**Comment by GregOriol** [comment]
Not sure how blocker this is yet, as Stripe seems to be quite cautious about their implementation, with still some work in progress up to July, 1st and many exceptions to be defined (https://stripe.com/fr-FR/guides/strong-customer-authentication#exemptions-to-strong-customer-authentication)

Do other plugins like Ayden already implement "SCA" or 3D-S for example?

**Comment by pierre** [comment]
> Do other plugins like Ayden already implement "SCA" or 3D-S for example?

For "SCA", I'm not sure, but 3D-S is quite common and has been well supported with some processors for years (including with Adyen).

**Comment by GregOriol** [comment]
@pierre There are some news from Stripe: it seems that we should use a new API called SetupIntent+ PaymentIntent as described here to re-use cards for off-session payments: https://stripe.com/docs/payments/cards/reusing-cards

What do you think about this? It's maybe time to upgrade the plugin?

**Comment by pierre** [comment]
> What do you think about this? It's maybe time to upgrade the plugin?

@GregOriol We've recently been working on Kill Bill AMIs specifically optimized for AWS workloads. These come with a rewritten Stripe plugin pre-bundled which fully supports the new [Payment Intents API](https://stripe.com/docs/payments/payment-intents), as well as the new Checkout and Stripe.js (using Elements) flows. So, these images should be SCA ready (all flavors of 3D-S are supported).

We are currently running a closed beta but if you are interested in being part of the program, I can let you know when we are ready to accept new testers. If you aren't running Kill Bill on AWS, we could also find a way to give you access to that plugin. Regardless, feel free to reach out to me directly (pierre@ our domain name).

As far as upgrading the Ruby plugin to support these new APIs, this is still pretty low on our (long) TODO list unfortunately.

**Comment by GregOriol** [comment]
Thanks for the update!

We are not running on AWS but on the Docker images. I'm sure this could be useful to some, even though it is not the ruby plugin that is updated. (actually, I guess that if an implementation is made available running on the Setup/Payment Intents APIs, it should be a new payment method/plugin, as it can't just replace the old one, the migration of the old tokens is not possible as far as I understand)

I'll get in touch by e-mail to get this going!

**Comment by pierre** [comment]
> As far as upgrading the Ruby plugin to support these new APIs, this is still pretty low on our (long) TODO list unfortunately.

A Java re-implementation of the plugin will be available shortly as part of the upcoming release of Kill Bill 0.22. SCA will now be supported.
