### ISSUE TITLE
ChargeBee Comparison?

### ISSUE THREAD

**Issue by dm17** [killbill/killbill-stripe-plugin#20]
I'm trying to implement Stripe & PayPal subscriptions for an e-commerce site in a consistent, congruent, and future-proof way. Any ideas on the best stuff out there for this? Of course I would prefer open source - not Chargebee - and considering implementing myself.

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [CONTRIBUTING.md](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
