### ISSUE TITLE
killbill-stripe-plugin integration tests failed

### ISSUE THREAD

**Issue by svroves** [killbill/killbill-stripe-plugin#5]
I configured killbill and is working when I run localhost:9090 on browser.
I configured killbill-stripe plugin. Build the project with the commands:
rvm use jruby
bundle install
jbundle install
rake killbill:clean
rake build
rake killbill:package

Stripe API are updated in stripe.yml, Note: I'm using MySQL database.

Now, when I run local test rake test:spec, it works and returns with "2 examples, 0 failures".
When I run rake test:remote:spec, it returns with "5 examples, 2 failures" for :- 
Create and retrieve payment methods
Charge a credit card directly

Checking the details of failure errors shows:
pms_found.size.should==2   Expected:2   Got: 10
StripeTransaction.all.size.should==0   Expected:0    Got: 36

If I go ahead and run curl command: 
curl -v \
     -u admin:password \
     -H "X-Killbill-ApiKey: bob" \
     -H "X-Killbill-ApiSecret: lazar" \
     -H "Content-Type: application/json" \
     -H "X-Killbill-CreatedBy: demo" \
     -X POST \
     --data-binary '{"pluginName":"killbill-stripe","pluginInfo":{"properties":[{"key":"token","value":"abcd"}]"}}' \
     "http://127.0.0.1:8080/1.0/kb/accounts/268983f2-5443-47e4-a967-b8962fc699c5/paymentMethods?isDefault=true"
Returns with Bad Request and error message as "plugin killbill-stripe is not registered"

Please help for the reason of the issue and suggest solution

**Comment by svroves** [comment]
After I renamed the folder from '0.2.3' to 'killbill-stripe-0.2.3', it resolved the issue.
But now I get "failed to add payment method for account ......... : undefined method 'tenant_user_api' for #<Killbill::Plugin:KillbillApi:0x61a4f60>"

Please help. Thanks

**Comment by pierre** [comment]
See discussion on the mailing-list: https://groups.google.com/d/msg/killbilling-users/kslfXaa2cMU/d22T5JHgSxQJ.
