### ISSUE TITLE
Stripe Dashboard Rendering

### ISSUE THREAD

**Issue by galenp** [killbill/killbill-stripe-plugin#6]
Hi Guys

We are doing some end-to-end testing of our payment integration and things are processing fine!

One thing that we don't really like tho is how the plugin records the details of the customer in stripe. We  would like to know if this can present better.... either through our own configuration or an adjustment to the plugin.

![image](https://cloud.githubusercontent.com/assets/1113659/7244531/80b2d0e6-e80f-11e4-9779-ad44b854491a.png)

Since we have the customer details in the KB billing account could we not have the information passed by the plugin a bit nicer to Stripe?

Or does the screenshot not look like how it does when you guys do it?

**Comment by galenp** [comment]
I guess the big issue here is the missing e-mail and the lack of the customer name making it through.

Galen

**Comment by pierre** [comment]
Stripe seems to have little metadata on the [customer object](https://stripe.com/docs/api#customer_object) and we need the description field to map it to the Kill Bill account id. I've just pushed a patch to populate the email address though.

For the customer name, you should have it on the card itself.
